# Generated by Django 3.2.8 on 2021-10-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1app', '0002_rename_products_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('pict', models.ImageField(upload_to='')),
                ('des', models.TextField()),
            ],
        ),
    ]
