# Generated by Django 3.2.8 on 2021-10-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1app', '0003_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='des',
            new_name='desc',
        ),
    ]
